# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
email: care@easycalculator.org
description: >- # this means to ignore newlines until "baseurl:"
  EasyCalculator.org is an open-source platform with free online calculators for math, science, and finance. Fast, accurate resultsâ€”no registration needed!.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://easycalculator.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

defaults:
  - scope:
    path: ""
    values:
    image: "/assets/images/android-chrome-512x512.png"



# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip 
  - jekyll-minifier 
 # - jekyll-robots.txt ( not require alredy used in root directory as custom)
 # - jekyll-last-modified-at ( gthub not support this plugin)



# Add the IndexNow integration
indexnow:
  api_key: "/d69eb464903242de9049154268ab5ef1.txt"  # Path to the key file you created

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#

include:
  - ".htaccess"


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6 # Table of Contents depth
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight" # Custom class for syntax highlighting (better styling control)
    line_numbers: true # Optional: Shows line numbers for code blocks
    start_line: 1 # Starting line number for line numbering
  parse_block_html: true # Allow HTML in Markdown (useful for SEO)
  math_engine: mathjax # Enable MathJax for math rendering (optional)








# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
  - "README.md"
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
